export const ADMIN_ROLES = [
  "ADMIN",
  "MENU_MANAGER",
  "ORDER_MANAGER",
  "INVENTORY_MANAGER",
  "PROMOTION_MANAGER",
  "FEEDBACK_MANAGER"
];

export const USER_ROLES = [
  "CUSTOMER",
  "ADMIN",
  "MENU_MANAGER",
  "ORDER_MANAGER",
  "INVENTORY_MANAGER",
  "PROMOTION_MANAGER",
  "FEEDBACK_MANAGER"
];
